package co.edu.unbosque.model.entity;

public enum NombreCuenta {
    CAJA,
    BANCOS,
    CUENTAS_POR_COBRAR,
    INVENTARIOS,
    PROPIEDADES,
    MAQUINARIAS,
    EQUIPOS,
    CUENTAS_POR_PAGAR,
    OBLIGACIONES_A_CORTO_PLAZO,
    PRESTAMOS_A_LARGO_PLAZO,
    CAPITAL_SOCIAL,
    APORTES_DE_SOCIOS,
    UTILIDADES_REVENIDAS,
    INGRESO_POR_VENTAS,
    INGRESO_POR_SERVICIOS,
    OTROS_INGRESOS,
    GASTOS_DE_ADMINISTRACION,
    GASTOS_DE_VENTAS,
    GASTOS_FINANCIEROS,
    IMPUESTOS;
}
