package co.edu.unbosque.model.entity;

public enum NombreCuenta {
    CAJA,
    CUENTAS_POR_COBRAR,
    INVENTARIOS,
    CUENTAS_POR_PAGAR,
    APORTES_DE_SOCIOS,
    UTILIDADES_REVENIDAS,
    INGRESO_POR_VENTAS,
    OTROS_INGRESOS,
    GASTOS_DE_ADMINISTRACION,
    GASTOS_DE_VENTAS,
    IMPUESTOS;
}